### PR TITLE
Add Drush based batch for disk images.

### PR DESCRIPTION
**Pull request by jordandukart**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2442

# What does this Pull Request do?
Adds a Drush based batch for ingesting disk images.

# What's new?
A batch.

# How should this be tested?
Package up a ZIP in the form scan batch expects and run the idip command to preprocess followed by ibi to ingest the set.

# Interested parties
@mjordan

### CODE REVIEW

**Review by qadan — APPROVED** [review]
Not a whole lot to review, is a batch and gets around the issue just fine 👍

**Comment by qadan** [comment]
Restarting a part of Travis; I think it should end up fine, just travis-related issues

**Comment by mjordan** [comment]
Hi guys, I'm travelling at the moment but will get to this on the weekend.

**Comment by mjordan** [comment]
`drush -v -u 1 --uri=http://localhost idip --type=directory --scan_target=/tmp/2442 --parent=islandora:sp_disk_image_collection --namespace=foo`

and

`drush -v -u 1 --uri=http://localhost idip --type=zip --scan_target=/tmp/2442.zip --parent=islandora:sp_disk_image_collection --namespace=foo`

both produce sets that ingest as expected.

**Pull request merged**
